### ISSUE TITLE
Instructions for running tensorboard over SSH [wiki]

### ISSUE THREAD

**Issue by harisriaz17** [AliceO2Group/TPCwithDNN#50]
See changes to the wiki here (under use of tensorboard section): https://github.com/harisriaz17/TPCwithDNN/wiki

Wiki clone URL:
https://github.com/harisriaz17/TPCwithDNN.wiki.git

**Comment by saganatt** [comment]
Hi,
sorry - didn't saw this issue earlier. Looks good, can you add it to the wiki in the main repo?
Thanks a lot!

**Comment by harisriaz17** [comment]
Alright, thanks!
